//! Pre-resolved `ResourceId`s for the founding 22 catalog resources.
//!
//! Hot paths shouldn't pay for `catalog.id_of("wood")` on every comparison.
//! `init_core_ids(catalog)` is called once at startup and writes the
//! `ResourceId` for each founding resource into a `OnceLock`. Call sites
//! reach the resolved id either via the snake-case accessor functions
//! generated by the [`core_ids!`] macro (e.g. `core_ids::wood()`) or via
//! the corresponding static (`*core_ids::Wood.get().unwrap()` — only for
//! sites that already pay the deref cost in a hot loop).

use std::sync::OnceLock;

use super::resource_catalog::{load_resource_catalog, ResourceCatalog, ResourceId};

/// Process-global cache of the loaded `ResourceCatalog`. Populated either
/// by an explicit `install_catalog()` call from `WorldPlugin::build` (the
/// production path) or lazily on first read via `catalog()` (the test
/// path, which doesn't go through the plugin). Both paths converge on the
/// same single load — `OnceLock::get_or_init` ensures no double-parsing.
///
/// Read-only after init: every consumer takes an `&'static ResourceCatalog`,
/// no locks needed in hot paths.
static GLOBAL_CATALOG: OnceLock<ResourceCatalog> = OnceLock::new();

/// Install a freshly-loaded catalog into the process-global slot and
/// populate the per-resource `OnceLock`s. Called by `WorldPlugin::build`
/// so the live game shares a single catalog instance with the snake-case
/// accessor functions. Subsequent calls are no-ops (the static is already
/// populated).
pub fn install_catalog(catalog: ResourceCatalog) {
    init_core_ids(&catalog);
    let _ = GLOBAL_CATALOG.set(catalog);
}

/// Borrow the global catalog. If neither `install_catalog` nor a prior
/// `catalog()` call has run, lazy-loads from `assets/data/resources/`
/// and runs `init_core_ids` as a side effect. Tests that bypass the
/// fixture / plugin (e.g. `simulation/carry.rs::tests`) rely on this
/// path so they don't have to thread setup through every test.
pub fn catalog() -> &'static ResourceCatalog {
    GLOBAL_CATALOG.get_or_init(|| {
        let cat = load_resource_catalog();
        init_core_ids(&cat);
        cat
    })
}

/// All catalog ResourceIds with `edible_calories` set, computed once. Drives
/// every "any food works" path (chief calorie postings via `ClaimKind::AnyEdible`,
/// `FactionStorage::food_total`, the chief's calorie-unit baseline). Adding a
/// new edible to `assets/data/resources/*.ron` automatically appears here on
/// next run — no Rust changes needed.
pub fn edibles() -> &'static [ResourceId] {
    static CACHE: OnceLock<Vec<ResourceId>> = OnceLock::new();
    CACHE.get_or_init(|| {
        catalog()
            .iter()
            .filter(|(_, d)| d.edible_calories.is_some())
            .map(|(id, _)| id)
            .collect()
    })
}

/// Conservative per-unit calorie baseline used by the chief's food-deficit
/// posting math. Picks the *minimum* edible calorie value in the catalog so
/// the chief never under-targets — depositing higher-calorie food just finishes
/// the posting faster. Falls back to 50 when the catalog has no edibles
/// (defensive; production catalogs always carry at least Fruit/Meat/Grain).
pub fn min_edible_calories() -> u32 {
    static CACHE: OnceLock<u32> = OnceLock::new();
    *CACHE.get_or_init(|| {
        let cat = catalog();
        edibles()
            .iter()
            .filter_map(|id| cat.get(*id).and_then(|d| d.edible_calories))
            .map(|c| c as u32)
            .min()
            .unwrap_or(50)
    })
}

/// Catalog-backed display name for a resource, returned with `'static`
/// lifetime so UI call sites can pass it directly to `format!` without
/// owning a `String`. The borrow is sound: `catalog()` returns
/// `&'static ResourceCatalog`, so the inner `String`'s slice lives as
/// long as the global. Used by UI panels (inspector, economy, debug)
/// for resource display.
pub fn display_name(id: ResourceId) -> &'static str {
    catalog()
        .get(id)
        .map(|d| d.display_name.as_str())
        .unwrap_or("?")
}

macro_rules! core_ids {
    ($( $name:ident => $key:literal => $snake:ident ),+ $(,)?) => {
        $(
            #[allow(non_upper_case_globals)]
            pub static $name: OnceLock<ResourceId> = OnceLock::new();

            /// Lazy snake-case accessor. First call lazy-loads the catalog
            /// and primes every core_ids `OnceLock`; subsequent reads are a
            /// single relaxed atomic load. Use this anywhere code wants
            /// "the ResourceId for <name>".
            pub fn $snake() -> ResourceId {
                let _ = catalog();
                *$name.get().expect(concat!(
                    "core_ids::", stringify!($snake),
                    "() read before init_core_ids() ran"
                ))
            }
        )+

        /// Resolve every founding resource's `ResourceId` from the catalog
        /// and install it in the matching `OnceLock`. Idempotent (re-init
        /// is a silent no-op via `OnceLock::set`'s `Result`). Called from
        /// `WorldPlugin::build` after the catalog is inserted.
        pub fn init_core_ids(catalog: &ResourceCatalog) {
            $(
                let id = catalog.id_of($key).unwrap_or_else(|| {
                    panic!(
                        "core_ids: catalog is missing required founding resource {:?}.",
                        $key
                    )
                });
                let _ = $name.set(id);
            )+
        }
    }
}

core_ids! {
    Fruit => "fruit" => fruit,
    Meat => "meat" => meat,
    Grain => "grain" => grain,
    Fish => "fish" => fish,
    PreservedFish => "preserved_fish" => preserved_fish,
    Wood => "wood" => wood,
    Stone => "stone" => stone,
    Tools => "tools" => tools,
    Cloth => "cloth" => cloth,
    Coal => "coal" => coal,
    Iron => "iron" => iron,
    Luxury => "luxury" => luxury,
    GrainSeed => "grain_seed" => grain_seed,
    Weapon => "weapon" => weapon,
    Bow => "bow" => bow,
    Sling => "sling" => sling,
    Armor => "armor" => armor,
    Shield => "shield" => shield,
    Skin => "skin" => skin,
    Copper => "copper" => copper,
    Tin => "tin" => tin,
    Gold => "gold" => gold,
    Silver => "silver" => silver,
    BerrySeed => "berry_seed" => berry_seed,
    ClayTablet => "clay_tablet" => clay_tablet,
    Book => "book" => book,
    Bedroll => "bedroll" => bedroll,
    PackedYurt => "packed_yurt" => packed_yurt,
    PreservedMeat => "preserved_meat" => preserved_meat,
    CleanWater => "clean_water" => clean_water,
    RawWater => "raw_water" => raw_water,
    ArdPlow => "ard_plow" => ard_plow,
    CartFrameSmall => "cart_frame_small" => cart_frame_small,
    CartFrameMedium => "cart_frame_medium" => cart_frame_medium,
    CartWheelWood => "cart_wheel_wood" => cart_wheel_wood,
    CartWheelIronrim => "cart_wheel_ironrim" => cart_wheel_ironrim,
    Knife => "knife" => knife,
    Axe => "axe" => axe,
    Pick => "pick" => pick,
    Hammer => "hammer" => hammer,
    Sickle => "sickle" => sickle,
    Awl => "awl" => awl,
    FishingKit => "fishing_kit" => fishing_kit,
    Bone => "bone" => bone,
}
